### ISSUE TITLE
thanks! 

### ISSUE THREAD

**Issue by solyaris** [kuzyn/chatscript-tmlanguage#28]
Hi Samuel

this is not an issue but just a thank you, so please label it as you want or close!

BTW, I enjoyed your syntax highlithing fo sublime text, I want to thank you for that! :)

In facts, Im a vim editor user and I would like to use thi highlighting with vim, see my request here:

http://vi.stackexchange.com/questions/8955/vim-syntax-highlighting-for-chatscript-language

As far as you know, there is maybe a CSON / tmlanguage converter/translator for vim editor vimscript ?

In case, I'll try to do my best to  build-one a vim syntax highlighting possibly using your regex here and mentioning your work, under your agreement.

Last but not least: enjoyable chatscript app, you done: https://twitter.com/solyarisoftware/status/757900684310286336

respect
giorgio

**Comment by kuzyn** [comment]
Hey there @solyaris, glad that you enjoy the package!

I have no knowledge of how vim syntaxes work, nor do I know of a converter. If there is, it's most probably a tmlanguage to vim converter, as tmlanguage is more widely used for syntax than CSON at this point.

Of course, feel free to use any or all part of this towards your own definition! However, two things to keep in mind:

A major difficulty of writing and maintaining syntax definition for CS is that the language is under active development. That is, the specs are not frozen and things are put in and taken out each week, which obviously makes the syntax impossible to be 100% accurate. I'd say that it hovers around the 90% mark in term of coverage and accuracy. 

Second difficulty is that CS is very forgiving in terms of character omission, letter case, function prefixes, etc. So instead of creating rules that mimic CS loose matching, my syntax is quite opinionated and enforce a certain coding style. This is quite uncommon for editor syntaxes.

**Comment by solyaris** [comment]
Thanks a lot Samuel!

All clear. I'll look for a tmlanguage to vimscript translator or I'll start setup the vimscript myself using your regex that sound pretty perfect on sublime text rendering :)

Yes ChatScript is now under active developement and that's a good news, I guess. I also understand the difficulty you experienced. Anyway I "agree" with your syntax choices! Opinable ok, but I have just to thank you again for now and I'l come to you if I'll have some news/proposals!

respect
giorgio

**Comment by kuzyn** [comment]
Great, let me know how it goes. Best
